### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ExplosionGaming** [OctoPussh/StaffChat#1]
Here's the crashdump:

Error: Call to a member function isOnline() on null
File: plugins/StaffChat.phar/src/octopush/staffchat/StaffChat
Line: 66
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: StaffChatX

Code:
[57] 	public function leaveStaffChat(CommandSender $sender): void {
[58] 		if (isset($this->staffChat[$sender->getName()])) unset($this->staffChat[$sender->getName()]);
[59] 		$announce = $this->getConfig()->get('announce-state', true);
[60] 		if (!$announce) return;
[61] 		$leaveFormat = $this->getConfig()->get('join',"&b%player% &fleft the staff chat");
[62] 		$leaveFormat = str_replace("%player%", $sender->getName(), $leaveFormat);
[63] 		$leaveMessage = $this->colorize($leaveFormat);
[64] 		foreach ($this->staffChat as $staff) {
[65] 			$staff = $this->getServer()->getPlayerExact($staff);
[66] 			if ($staff->isOnline() && $staff->hasPermission(self::READ_PERMISSION)) {
[67] 				$staff->sendMessage($leaveMessage);
[68] 			}
[69] 		}
[70] 	}
[71] 
[72] 	/**
[73] 	 * @param CommandSender $sender
[74] 	 * @return bool
[75] 	 */
[76] 	public function inStaffChat(CommandSender $sender): bool {

Backtrace:
#0 plugins/StaffChat.phar/src/octopush/staffchat/command/StaffChatCommand(51): octopush\staffchat\StaffChat->leaveStaffChat(object pocketmine\player\Player#120004)
#1 pmsrc/src/command/SimpleCommandMap(220): octopush\staffchat\command\StaffChatCommand->execute(object pocketmine\player\Player#120004, string[2] sc, array[1])
#2 pmsrc/src/Server(1406): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#120004, string[6] sc off)
#3 pmsrc/src/player/Player(1342): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#120004, string[6] sc off)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(688): pocketmine\player\Player->chat(string[7] /sc off)
#5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(60): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#127023)
#6 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#120383)
#7 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#127023, string[28] M./sc off..Ol.....5.XW......)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] ..e./NV.OKc8...i....L.#..5.-b`..)
#9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[41] ...mJ@...]*............t.Aq?...o_.]..'B..)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#30965)
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/src/Server(1657): pocketmine\snooze\SleeperHandler->sleepUntil(double 1642032340.0993)
#14 pmsrc/src/Server(1044): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[48] /home/minecraft/multicraft/servers/server226389/, string[56] /home/minecraft/multicraft/servers/server226389/plugins/)
#16 pmsrc/src/PocketMine(326): pocketmine\server()
#17 pmsrc(11): require(string[92] phar:///home/minecraft/multicraft/servers/server226389/PocketMine-MP.phar/src/Po)

PocketMine-MP version: 4.0.4 [Protocol 475]
Git commit: b903e90dc29abc5ef1c6845012fdaea7e19a75de
uname -a: Linux 80ea0033c3af 4.4.232-1.el7.elrepo.x86_64 #1 SMP Fri Jul 31 11:49:26 EDT 2020 x86_64
PHP Version: 8.0.13
Zend version: 4.0.13
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.5.0+bedrock-1.18.0@482c679aa5ed0b81c088c2b1ff0b8110a94c8a6c
- pocketmine/bedrock-protocol 7.1.0+bedrock-1.18.0@42f2a00634c17c346fd98c05b2daf29d1fbf5805
- pocketmine/binaryutils 0.2.3@dc94786fc6c30012b1892f548dbb8a8c9c0a8cd9
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.3.0@ec742b209e8056bbe855069c4eff94c9734ea19b
- pocketmine/locale-data 2.2.1@9fdd36f0ac3a2dfe1acacbee8b23eb6615129701
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.0.4@b903e90dc29abc5ef1c6845012fdaea7e19a75de
- pocketmine/raklib 0.14.2@e3a861187470e1facc6625040128f447ebbcbaec
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.23.0@46cd95797e9df938fdd2b03693b5fca5e64b01ce
- symfony/polyfill-php80 v1.23.1@1100343ed1a92e3a38f9ae122fc0eb21602547be
- symfony/polyfill-php81 v1.23.0@e66119f3de95efc359483f810c4c3e6436279436
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

Loaded plugins:
AlwaysSpawn 2.2.5 by Philip Shilling for API(s) 4.0.0
BetterBan 4.0.1 by supercrfafter333 for API(s) 4.0.0
EasyEdit 2.0.1 by platz1de for API(s) 4.0.0
HideCommands 2.0.0 by Himbeer for API(s) 4.0.0
Mineflow 2.6.1 by aieuo for API(s) 4.0.0
MultiWorld 1.7.0-beta3 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 4.0.0
Netherite 2.0 by Wertzui123 for API(s) 4.0.0
PlayerTags 2.0.0 by sylvrs for API(s) 4.0.0
PureChat 2.0.0 by Vecnavium, 64FF00 for API(s) 4.0.0
PurePerms 1.4.4 by Vecnavium , 64FF00 & ProjectInfinity for API(s) 4.0.0
Shield 1.4.0 by JavierLeon9966 for API(s) 4.0.0
ShowPerms 2.0.0 by ethaniccc, mmm545 for API(s) 4.0.0
StaffChatX 1.0-alpha by Octopush for API(s) 4.0.0
WorldProtect 2.3.10 by aliuly for API(s) 4.0.0

**Comment by OctoPussh** [comment]
Thanks for reporting the issue, I'll fix this in a bit :)

**Comment by ExplosionGaming** [comment]
> @ExplosionGaming Could you test the fix please [95c1067](https://github.com/OctoPussh/StaffChat/commit/95c1067c24beb91e994731aa97343ab03a0d8432)

Sorry dude. I'll check it in the morning.
